### ISSUE TITLE
Heroku suspension

### ISSUE THREAD

**Issue by Subhranta66** [Zylern/TGVid-Comp#3]
Please do modify some code .. so i can install in heroku.. thank you

**Comment by Zylern** [comment]
Heroku suspended repo try to fork this repo and deploy your forked one.
If it doesn't work then use <a href='https://t.me/XTZ_HerokuBot'>@XTZ_HerokuBot</a> bot to deploy the repo.

**Comment by Subhranta66** [comment]
Thanks for ur concern..now working..👍
