### ISSUE TITLE
Can't able to add config variables on okteto

### ISSUE THREAD

**Issue by dvrajput** [Zylern/TGVid-Comp#8]
it is start direct deploying....

**Comment by Zylern** [comment]
Fork the repo then login to your Okteto account after that give okteto permissions to access your repos then deploy from there.

**Comment by dvrajput** [comment]
This is i done before, but still it showing error about variables

**Comment by Zylern** [comment]
Message me on telegram i will tell you how to deploy.

**Comment by Zylern** [comment]
First Open This [Link](https://cloud.okteto.com/#/deploy?repository=https://github.com/Zylern/TGVid-Comp&vars=[{"name":"APP_ID","value":"Your App Id"},{"name":"API_HASH","value":"Your Api Hash"},{"name":"BOT_TOKEN","value":"BotToken"},{"name":"OWNER","value":"OwnerId"},{"name":"THUMBNAIL","value":"https://telegra.ph/file/f9e5d783542906418412d.jpg"}]) it will start deploying automatically after deploying click on redeploy button then fill your variables.

**Comment by Zylern** [comment]
Pm me on telegram.

**Comment by Zylern** [comment]
Click on the deploy button it will start deploying automatically after deploying click on redeploy button then fill your variables and deploy it again.
Like shown in the image below.

![IMG](https://user-images.githubusercontent.com/47510180/165902456-80705e5a-a7cd-4c93-b495-a23e6f2315cc.jpg)
